In [23]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [24]:
crime = pd.read_csv('../Data/Crime/Crime.csv')

crime.sample()

TL Territory level and Typology REG_ID           Region           VAR  \
873   1                      Country    SVK  Slovak Republic  VEH_THEFT_RA   

                                             Indicator  POS     Position  \
873  Motor Vehicle Theft Rate (vehicule theft for 1...  ALL  All regions   

     TIME  Year  Unit Code  Unit  PowerCode Code PowerCode  \
873  2005  2005        NaN   NaN               0     Units   

     Reference Period Code  Reference Period  Value Flag Codes Flags  
873                    NaN               NaN  103.9        NaN   NaN

In [25]:
crime.shape

(2115, 19)

In [26]:
crime.isnull().sum()

TL                                 0
Territory level and Typology       0
REG_ID                             0
Region                             0
VAR                                0
Indicator                          0
POS                                0
Position                           0
TIME                               0
Year                               0
Unit Code                       2115
Unit                            2115
PowerCode Code                     0
PowerCode                          0
Reference Period Code           2115
Reference Period                2115
Value                              0
Flag Codes                      2111
Flags                           2111
dtype: int64

In [27]:
crime['TL'].unique()

array([1], dtype=int64)

In [28]:
crime.Region.unique()

array(['Australia', 'Austria', 'Belgium', 'Canada', 'France', 'Germany',
       'United Kingdom', 'Russia', 'Greece', 'Hungary', 'Iceland',
       'Ireland', 'Netherlands', 'New Zealand', 'Norway', 'Poland',
       'United States', 'Israel', 'Italy', 'Japan', 'Portugal',
       'Slovak Republic', 'Slovenia', 'Spain', 'Chile', 'Czech Republic',
       'Denmark', 'Estonia', 'Finland', 'Korea', 'Luxembourg', 'Mexico',
       'Sweden', 'Switzerland', 'Turkey', 'Colombia', 'Lithuania',
       'Latvia', 'OECD'], dtype=object)

In [29]:
len(crime.Region.unique())

39

In [30]:
crime.POS.unique()

array(['ALL'], dtype=object)

In [31]:
crime.Year.unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016], dtype=int64)

In [32]:
crime['PowerCode Code'].unique()

array([0], dtype=int64)

In [33]:
crime.PowerCode.unique()

array(['Units'], dtype=object)

In [34]:
crime.VAR.unique()

array(['HOMIC', 'HOMIC_RA', 'VEH_THEFT', 'VEH_THEFT_RA', 'MORT_TRANSP_RA'],
      dtype=object)

In [46]:
crime['Indicator'].unique()

array(['Intentional Homicides (number)',
       'Intentional Homicide Rate (homicides for 100 000 population)',
       'Motor Vehicle Theft Rate (number)',
       'Motor Vehicle Theft Rate (vehicule theft for 10 000 population)',
       'Mortality rate due to transport accident (deaths for  100 000 population)'],
      dtype=object)

In [49]:
crime[['VAR', 'Indicator']][:4]

VAR                                          Indicator
0         HOMIC                     Intentional Homicides (number)
1      HOMIC_RA  Intentional Homicide Rate (homicides for 100 0...
2     VEH_THEFT                  Motor Vehicle Theft Rate (number)
3  VEH_THEFT_RA  Motor Vehicle Theft Rate (vehicule theft for 1...

In [56]:
crime[crime['Indicator'] == 'Mortality rate due to transport accident (deaths for  100 000 population)']['VAR'].unique()

array(['MORT_TRANSP_RA'], dtype=object)

In [41]:
columns = ['TL', 'Territory level and Typology', 'REG_ID', 'POS', 'Position', 'TIME', 'Unit Code', 'Unit', 'PowerCode Code', 'PowerCode', 'Reference Period Code', 'Reference Period', 'Flag Codes', 'Flags']

crime_df = crime.drop(columns=columns)
crime_df.sample()

Region           VAR                                          Indicator  \
1776  Canada  VEH_THEFT_RA  Motor Vehicle Theft Rate (vehicule theft for 1...   

      Year  Value  
1776  2015  219.8

## 국가별 강력범죄 수

In [43]:
px.line(crime_df[crime_df['VAR'] == 'HOMIC'], x='Year', y='Value', color='Region')

## 국가별 강력범죄 발생률

In [44]:
px.line(crime_df[crime_df['VAR'] == 'HOMIC_RA'], x='Year', y='Value', color='Region')

## 국가별 차량 절도 수

In [47]:
px.line(crime_df[crime_df['VAR'] == 'VEH_THEFT'], x='Year', y='Value', color='Region')

## 국가별 차량절도 비율

In [57]:
px.line(crime_df[crime_df['VAR'] == 'VEH_THEFT_RA'], x='Year', y='Value', color='Region')

## 교통사고 사망률

In [63]:
px.line(crime_df[crime_df['VAR'] == 'MORT_TRANSP_RA'], x='Year', y='Value', color='Region')

## 한국

In [60]:
crime_df[crime_df['Region'] == 'Korea']

Region       VAR                                          Indicator  \
1166  Korea     HOMIC                     Intentional Homicides (number)   
1167  Korea  HOMIC_RA  Intentional Homicide Rate (homicides for 100 0...   
1168  Korea     HOMIC                     Intentional Homicides (number)   
1169  Korea  HOMIC_RA  Intentional Homicide Rate (homicides for 100 0...   
1170  Korea     HOMIC                     Intentional Homicides (number)   
1171  Korea  HOMIC_RA  Intentional Homicide Rate (homicides for 100 0...   
1172  Korea     HOMIC                     Intentional Homicides (number)   
1173  Korea  HOMIC_RA  Intentional Homicide Rate (homicides for 100 0...   
1174  Korea     HOMIC                     Intentional Homicides (number)   
1175  Korea  HOMIC_RA  Intentional Homicide Rate (homicides for 100 0...   
1176  Korea     HOMIC                     Intentional Homicides (number)   
1177  Korea  HOMIC_RA  Intentional Homicide Rate (homicides for 100 0...   
1178  Korea     HOMIC                     Intentional Homicides (number)   
1179  Korea  HOMIC_RA  Intentional Homicide Rate (homicides for 100 0...   
1698  Korea  HOMIC_RA  Intentional Homicide Rate (homicides for 100 0...   
1718  Korea     HOMIC                     Intentional Homicides (number)   
1720  Korea  HOMIC_RA  Intentional Homicide Rate (homicides for 100 0...   
1762  Korea     HOMIC                     Intentional Homicides (number)   

      Year   Value  
1166  2007  1104.0  
1167  2007     2.3  
1168  2008  1099.0  
1169  2008     2.2  
1170  2009  1366.0  
1171  2009     2.8  
1172  2010  1240.0  
1173  2010     2.5  
1174  2011   989.0  
1175  2011     2.0  
1176  2012   784.0  
1177  2012     1.6  
1178  2013   755.0  
1179  2013     1.5  
1698  2015     1.5  
1718  2015   759.0  
1720  2014     1.5  
1762  2014   738.0

In [59]:
px.line(crime_df[crime_df['Region'] == 'Korea'], x='Year', y='Value', color='Indicator')